{% set name = "flake8-import-style" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8-import-style-{{ version }}.tar.gz
  sha256: f576fe09460e39b7b474d4249823b9c6c2e1be63c5e1e538d262d4d019dd134b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - flake8_import_style
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sfstpala/flake8-import-style
  summary: A flake8 plugin to ensure explicit module imports
  license: ISC
  license_file: COPYING

extra:
  recipe-maintainers:
    - apmorton
